# Generated by Django 5.2.8 on 2026-01-21 11:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='None')),
                ('exc_type', models.CharField(default='None')),
                ('exc_value', models.CharField(default='None')),
                ('lineno', models.CharField(default='None')),
                ('datetime_field', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
