# Generated by Django 5.2.8 on 2026-01-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cis', models.CharField(default='None', max_length=150)),
                ('gtin', models.CharField(default='None', max_length=150)),
                ('productName', models.CharField(default='None', max_length=150)),
                ('applicationDate', models.CharField(default='None', max_length=150)),
                ('introducedDate', models.CharField(default='None', max_length=150)),
                ('manufacturerInn', models.CharField(default='None', max_length=150)),
                ('manufacturerName', models.CharField(default='None', max_length=150)),
                ('requestedCis', models.CharField(default='None', max_length=150)),
                ('tnVedEaes', models.CharField(default='None', max_length=150)),
                ('tnVedEaesGroup', models.CharField(default='None', max_length=150)),
                ('productGroupId', models.IntegerField(default='None')),
                ('productGroup', models.CharField(default='None', max_length=150)),
                ('brand', models.CharField(default='None', max_length=150)),
                ('producedDate', models.CharField(default='None', max_length=150)),
                ('emissionDate', models.CharField(default='None', max_length=150)),
                ('emissionType', models.CharField(default='None', max_length=150)),
                ('packageType', models.CharField(default='None', max_length=150)),
                ('generalPackageType', models.CharField(default='None', max_length=150)),
                ('ownerInn', models.CharField(default='None', max_length=150)),
                ('ownerName', models.CharField(default='None', max_length=150)),
                ('status', models.CharField(default='None', max_length=150)),
                ('statusEx', models.CharField(default='None', max_length=150)),
                ('producerInn', models.CharField(default='None', max_length=150)),
                ('producerName', models.CharField(default='None', max_length=150)),
                ('expirationDate', models.CharField(default='None', max_length=150)),
            ],
        ),
    ]
