# Generated by Django 5.2.8 on 2026-01-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycodes',
            name='child',
            field=models.CharField(default='None'),
        ),
    ]
